services:
  redis-server:
    image: redis:7.2.4
    environment: 
      - REDIS_ARGS=--save 30 1
    ports:
      - 6379:6379
    volumes:
      - ../db/data:/data # Mount the data directory to the container
    networks:
      - backend

  redis-data-loader:
    image: redis:7.2.4
    depends_on:
      - redis-server
    volumes:
      - ../db/scripts:/scripts  
    entrypoint: ["/scripts/load.sh"]
    networks:
      - backend


  redis-data-loader-dev:
    profiles: [dev]
    image: redis:7.2.4
    depends_on:
      redis-server:
        condition: service_started
    volumes:
      - ../db/scripts:/scripts  
    entrypoint: ["/scripts/load.dev.sh"]
    networks:
      - backend

  redis-data-loader-prod:
    profiles: [prod]
    image: redis:7.2.4
    depends_on:
      redis-server:
        condition: service_started
    volumes:
      - ../db/scripts:/scripts  
    entrypoint: ["/scripts/load.prod.sh"]
    networks:
      - backend
